# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-18 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WineDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('region_1', models.CharField(max_length=50)),
                ('region_2', models.CharField(max_length=50)),
                ('variety', models.CharField(max_length=255)),
                ('winery', models.CharField(max_length=255)),
            ],
        ),
    ]
