# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-18 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='winedetail',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='winedetail',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='winedetail',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='winedetail',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='winedetail',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='winedetail',
            name='province',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='winedetail',
            name='region_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='winedetail',
            name='region_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='winedetail',
            name='variety',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='winedetail',
            name='winery',
            field=models.CharField(default='', max_length=255),
        ),
    ]
